# Generated by Django 2.0.1 on 2018-02-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycriterion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='criterion',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criterion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
