# Generated by Django 2.0.1 on 2018-02-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_auto_20180204_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorycriterion',
            old_name='category',
            new_name='name',
        ),
    ]
