# Generated by Django 2.0.1 on 2018-02-24 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0003_auto_20180207_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='criteria.CategoryCriterion'),
        ),
    ]
