# Generated by Django 2.0.1 on 2018-03-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0004_auto_20180224_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycriterion',
            name='university_only',
            field=models.BooleanField(default=False),
        ),
    ]
