# Generated by Django 2.0.1 on 2018-03-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0022_auto_20180326_0517'),
        ('subject', '0022_auto_20180318_0202'),
        ('criteria', '0005_categorycriterion_university_only'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryCriterion',
            new_name='CriterionCategory',
        ),
    ]
