# Generated by Django 2.0.1 on 2018-03-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0006_auto_20180326_0857'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='criterioncategory',
            table='criterion_category',
        ),
    ]
