# Generated by Django 2.0.3 on 2018-04-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'criterion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CriterionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('university_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'criterion_category',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='criterion.CriterionCategory'),
        ),
    ]
