# Generated by Django 2.0.1 on 2018-07-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['category', 'id']},
        ),
        migrations.AlterModelOptions(
            name='criterioncategory',
            options={'ordering': ['-university_only', 'id']},
        ),
    ]
