# Generated by Django 2.0.4 on 2018-07-28 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0002_auto_20180709_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['category', 'id'], 'verbose_name': 'Tiêu chí so sánh', 'verbose_name_plural': 'Các tiêu chí so sánh'},
        ),
        migrations.AlterModelOptions(
            name='criterioncategory',
            options={'ordering': ['id'], 'verbose_name': 'Nhóm tiêu chí', 'verbose_name_plural': 'Các nhóm tiêu chí'},
        ),
        migrations.RemoveField(
            model_name='criterioncategory',
            name='university_only',
        ),
    ]
