# Generated by Django 2.0.4 on 2018-07-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0003_auto_20180728_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='criterion.CriterionCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='criterioncategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
    ]
