from .sector_form import AddSectorForm, UpdateSectorForm, RemoveSectorForm
from .favoutite_university_form import AddFavouriteUniversityForm, RemoveFavouriteUniversityForm
from .manage_university_form import AddUniversitySectorForm, RemoveUniversitySectorForm