# Generated by Django 2.0.3 on 2018-04-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subject',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subject_group',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectScoreByCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'subject_score',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectScoreByCriterionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'subject_score_by_category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UniversitySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(blank=True, default=0)),
                ('rank', models.IntegerField(blank=True, default=-1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='subject.Subject')),
            ],
            options={
                'db_table': 'university_subject',
                'ordering': ['id'],
            },
        ),
    ]
