# Generated by Django 2.0.3 on 2018-04-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('criterion', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitysubject',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_set', to='university.University'),
        ),
        migrations.AddField(
            model_name='subjectscorebycriterioncategory',
            name='criterion_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.CriterionCategory'),
        ),
        migrations.AddField(
            model_name='subjectscorebycriterioncategory',
            name='univ_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_category_scores', to='subject.UniversitySubject'),
        ),
        migrations.AddField(
            model_name='subjectscorebycriterion',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.Criterion'),
        ),
        migrations.AddField(
            model_name='subjectscorebycriterion',
            name='univ_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='subject.UniversitySubject'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='subject.SubjectGroup'),
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='subject.SubjectGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='universitysubject',
            unique_together={('university', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectscorebycriterioncategory',
            unique_together={('univ_subject', 'criterion_category')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectscorebycriterion',
            unique_together={('univ_subject', 'criterion')},
        ),
    ]
