# Generated by Django 2.0.3 on 2018-04-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20180405_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitysubject',
            old_name='overall_score',
            new_name='avg_score',
        ),
    ]
