# Generated by Django 2.0.1 on 2018-02-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_groupsubject_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
