# Generated by Django 2.0.3 on 2018-04-09 08:10

import score.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20180405_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectscorebycriterion',
            name='score',
            field=models.FloatField(default=0, validators=[score.validators.ScoreValidator()]),
        ),
        migrations.AlterField(
            model_name='subjectscorebycriterioncategory',
            name='score',
            field=models.FloatField(default=0, validators=[score.validators.ScoreValidator()]),
        ),
    ]
