# Generated by Django 2.0.1 on 2018-07-09 10:03

from django.db import migrations, models
import score.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20180409_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sector',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UniversitySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'university_sector',
                'ordering': ['id'],
            },
            bases=(models.Model, score.mixins.ScoreOwnerMixin, score.mixins.ScoreParserMixin),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subjectgroup',
            name='sector',
        ),
        migrations.AlterUniqueTogether(
            name='subjectscorebycriterion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subjectscorebycriterion',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='subjectscorebycriterion',
            name='univ_subject',
        ),
        migrations.AlterUniqueTogether(
            name='subjectscorebycriterioncategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subjectscorebycriterioncategory',
            name='criterion_category',
        ),
        migrations.RemoveField(
            model_name='subjectscorebycriterioncategory',
            name='univ_subject',
        ),
        migrations.AlterUniqueTogether(
            name='universitysubject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='universitysubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='universitysubject',
            name='university',
        ),
    ]
