# Generated by Django 2.0.1 on 2018-02-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20180201_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectscore',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectscore',
            name='university',
        ),
    ]
