# Generated by Django 2.0.1 on 2018-02-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20180202_0615'),
        ('subject', '0005_auto_20180202_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectscore',
            name='u_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.UniversitySubject'),
            preserve_default=False,
        ),
    ]
