# Generated by Django 2.0.1 on 2018-07-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20180709_1703'),
        ('university', '0007_auto_20180709_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectGroup',
        ),
        migrations.DeleteModel(
            name='SubjectScoreByCriterion',
        ),
        migrations.DeleteModel(
            name='SubjectScoreByCriterionCategory',
        ),
        migrations.DeleteModel(
            name='UniversitySubject',
        ),
        migrations.AddField(
            model_name='universitysector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='subject.Sector'),
        ),
        migrations.AddField(
            model_name='universitysector',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_set', to='university.University'),
        ),
        migrations.AlterUniqueTogether(
            name='universitysector',
            unique_together={('university', 'sector')},
        ),
    ]
