# Generated by Django 2.0.4 on 2018-07-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_auto_20180728_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='universitysector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='subject.Sector', verbose_name='Nhóm ngành'),
        ),
        migrations.AlterField(
            model_name='universitysector',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_set', to='university.University', verbose_name='Đại hoc'),
        ),
    ]
