# Generated by Django 2.0.1 on 2018-02-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_auto_20180202_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectscore',
            name='u_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='university.UniversitySubject'),
        ),
    ]
