# Generated by Django 2.0.4 on 2018-08-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_auto_20180807_2112'),
        ('subject', '0008_auto_20180731_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='universities',
            field=models.ManyToManyField(related_name='sector_set', through='subject.UniversitySector', to='university.University'),
        ),
        migrations.AlterField(
            model_name='universitysector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities_set', to='subject.Sector', verbose_name='Nhóm ngành'),
        ),
        migrations.AlterField(
            model_name='universitysector',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors_set', to='university.University', verbose_name='Đại hoc'),
        ),
    ]
