# Generated by Django 2.0.1 on 2018-02-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_auto_20180202_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsubject',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subjectscore',
            options={'ordering': ['id']},
        ),
    ]
