# Generated by Django 2.0.1 on 2018-02-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_auto_20180205_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectscorebycategory',
            old_name='criterion',
            new_name='category_criterion',
        ),
    ]
