# Generated by Django 2.0.1 on 2018-02-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0012_auto_20180205_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectscore',
            old_name='u_subject',
            new_name='univ_subject',
        ),
    ]
