# Generated by Django 2.0.1 on 2018-03-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0017_auto_20180228_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='subject.GroupSubject'),
        ),
    ]
