# Generated by Django 2.0.1 on 2018-03-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_auto_20180312_0836'),
        ('criteria', '0004_auto_20180224_0247'),
        ('subject', '0018_auto_20180305_1351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectscore',
            unique_together={('score_by_category', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectscorebycategory',
            unique_together={('univ_subject', 'category_criterion')},
        ),
    ]
