# Generated by Django 2.0.1 on 2018-03-17 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0020_auto_20180315_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectscore',
            name='score_by_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cri_scores', to='subject.SubjectScoreByCategory'),
        ),
    ]
