# Generated by Django 2.0.1 on 2018-03-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0023_auto_20180326_0857'),
        ('criteria', '0006_auto_20180326_0857'),
        ('subject', '0022_auto_20180318_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectscorebycategory',
            old_name='category_criterion',
            new_name='criterion_category',
        ),
        migrations.AlterUniqueTogether(
            name='subjectscorebycategory',
            unique_together={('univ_subject', 'criterion_category')},
        ),
    ]
