# Generated by Django 2.0.3 on 2018-04-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterion', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, null=True)),
                ('name', models.CharField(max_length=100)),
                ('overview', models.TextField(blank=True, null=True)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('overall_score', models.FloatField(default=0)),
                ('rank', models.IntegerField(default=-1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_universities', to='university.University')),
                ('subjects', models.ManyToManyField(through='subject.UniversitySubject', to='subject.Subject')),
            ],
            options={
                'db_table': 'university',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UniversityScoreByCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.Criterion')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='university.University')),
            ],
            options={
                'db_table': 'university_score',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UniversityScoreByCriterionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('criterion_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.CriterionCategory')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_category_scores', to='university.University')),
            ],
            options={
                'db_table': 'university_score_by_category',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='universityscorebycriterioncategory',
            unique_together={('university', 'criterion_category')},
        ),
        migrations.AlterUniqueTogether(
            name='universityscorebycriterion',
            unique_together={('university', 'criterion')},
        ),
    ]
