# Generated by Django 2.0.1 on 2018-02-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criteria', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, null=True)),
                ('name', models.CharField(max_length=100)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ranking_position', models.IntegerField(default=-1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.University')),
                ('subjects', models.ManyToManyField(through='subject.SubjectScore', to='subject.Subject')),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='UniversityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.Criterion')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University')),
            ],
            options={
                'db_table': 'university_score',
            },
        ),
    ]
