# Generated by Django 2.0.1 on 2018-02-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20180202_0615'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject')),
            ],
            options={
                'db_table': 'university_subject',
            },
        ),
        migrations.AlterField(
            model_name='university',
            name='subjects',
            field=models.ManyToManyField(through='university.UniversitySubject', to='subject.Subject'),
        ),
        migrations.AddField(
            model_name='universitysubject',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
    ]
