# Generated by Django 2.0.3 on 2018-04-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='overall_score',
            new_name='avg_score',
        ),
    ]
