# Generated by Django 2.0.1 on 2018-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20180202_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='subjects',
            field=models.ManyToManyField(related_name='subject_set', through='university.UniversitySubject', to='subject.Subject'),
        ),
    ]
