# Generated by Django 2.0.3 on 2018-04-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20180405_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='address',
        ),
        migrations.RemoveField(
            model_name='university',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='university',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='university',
            name='site_url',
        ),
        migrations.AlterField(
            model_name='university',
            name='code',
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
    ]
