# Generated by Django 2.0.1 on 2018-02-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20180202_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='subjects',
            field=models.ManyToManyField(through='university.UniversitySubject', to='subject.Subject'),
        ),
        migrations.AlterField(
            model_name='universitysubject',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_set', to='university.University'),
        ),
    ]
