# Generated by Django 2.0.3 on 2018-04-06 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20180406_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProfile',
            fields=[
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='university.University')),
                ('overview', models.TextField(blank=True, null=True)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'university_profile',
                'ordering': ['university'],
            },
        ),
    ]
