# Generated by Django 2.0.1 on 2018-02-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20180202_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='universityscore',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='universitysubject',
            options={'ordering': ['id']},
        ),
    ]
