# Generated by Django 2.0.3 on 2018-04-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_universityprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityprofile',
            name='image_path',
        ),
        migrations.AddField(
            model_name='university',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
