# Generated by Django 2.0.1 on 2018-02-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_auto_20180204_0717'),
        ('university', '0005_auto_20180204_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityScoreByCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('criterion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criteria.CategoryCriterion')),
            ],
            options={
                'db_table': 'university_score_by_category',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='universityscore',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criteria.Criterion'),
        ),
        migrations.AddField(
            model_name='universityscore',
            name='score_by_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.UniversityScoreByCategory'),
            preserve_default=False,
        ),
    ]
