# Generated by Django 2.0.1 on 2018-07-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20180709_1703'),
        ('university', '0006_auto_20180409_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='subjects',
        ),
        migrations.AddField(
            model_name='university',
            name='sector',
            field=models.ManyToManyField(through='subject.UniversitySector', to='subject.Sector'),
        ),
    ]
