# Generated by Django 2.0.1 on 2018-02-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20180205_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityscore',
            name='score_by_category',
        ),
    ]
