# Generated by Django 2.0.4 on 2018-07-28 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0007_auto_20180709_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'User University',
                'verbose_name_plural': 'User Universities',
                'db_table': 'user_university',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['id'], 'verbose_name': 'Đại hoc', 'verbose_name_plural': 'Các trường Đại học'},
        ),
        migrations.AlterModelOptions(
            name='universityprofile',
            options={'ordering': ['university'], 'verbose_name': 'Thông tin trường Đại học', 'verbose_name_plural': 'Thông tin trường Đại học'},
        ),
        migrations.AlterModelOptions(
            name='universityscorebycriterion',
            options={'ordering': ['id'], 'verbose_name': 'Điểm theo Tiêu chí', 'verbose_name_plural': 'Điểm theo Tiêu chí'},
        ),
        migrations.AlterModelOptions(
            name='universityscorebycriterioncategory',
            options={'ordering': ['id'], 'verbose_name': 'Điểm theo Nhóm tiêu chí', 'verbose_name_plural': 'Điểm theo nhóm tiêu chí'},
        ),
        migrations.AddField(
            model_name='useruniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='university.University'),
        ),
        migrations.AddField(
            model_name='useruniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useruniversity',
            unique_together={('user', 'university')},
        ),
    ]
