# Generated by Django 2.0.4 on 2018-07-28 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0008_auto_20180728_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouriteUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='university.University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User University',
                'verbose_name_plural': 'User Universities',
                'db_table': 'user_university',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='useruniversity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='useruniversity',
            name='university',
        ),
        migrations.RemoveField(
            model_name='useruniversity',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserUniversity',
        ),
        migrations.AlterUniqueTogether(
            name='userfavouriteuniversity',
            unique_together={('user', 'university')},
        ),
    ]
