# Generated by Django 2.0.1 on 2018-02-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_remove_universityscore_score_by_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityscore',
            name='score_by_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.UniversityScoreByCategory'),
            preserve_default=False,
        ),
    ]
