# Generated by Django 2.0.4 on 2018-07-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20180728_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavouriteuniversity',
            options={'ordering': ['id'], 'verbose_name': 'User - Favourite University', 'verbose_name_plural': 'User - Favourite Universities'},
        ),
    ]
