# Generated by Django 2.0.1 on 2018-02-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20180205_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityscore',
            name='score_by_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.UniversityScoreByCategory'),
        ),
    ]
