# Generated by Django 2.0.4 on 2018-07-28 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0010_auto_20180728_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagerUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='university.University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User - Manager University',
                'verbose_name_plural': 'User - Manager Universities',
                'db_table': 'user_manager_university',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelTable(
            name='userfavouriteuniversity',
            table='user_favourite_university',
        ),
        migrations.AlterUniqueTogether(
            name='usermanageruniversity',
            unique_together={('user', 'university')},
        ),
    ]
