# Generated by Django 2.0.1 on 2018-02-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20180205_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityscore',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='university.University'),
        ),
    ]
