# Generated by Django 2.0.4 on 2018-07-28 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20180728_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavouriteuniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_users_set', to='university.University'),
        ),
        migrations.AlterField(
            model_name='userfavouriteuniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_universities_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermanageruniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_users_set', to='university.University'),
        ),
        migrations.AlterField(
            model_name='usermanageruniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_universities_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
