# Generated by Django 2.0.4 on 2018-07-31 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import score.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0008_auto_20180731_0832'),
        ('university', '0012_auto_20180728_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavouriteuniversity',
            options={'ordering': ['id'], 'verbose_name': 'Người dùng - Trường yêu thích', 'verbose_name_plural': 'Người dùng - Trường yêu thích'},
        ),
        migrations.AlterModelOptions(
            name='usermanageruniversity',
            options={'ordering': ['id'], 'verbose_name': 'Người dùng - Trường quản lý', 'verbose_name_plural': 'Người dùng - Trường quản lý'},
        ),
        migrations.RemoveField(
            model_name='university',
            name='sector',
        ),
        migrations.AddField(
            model_name='university',
            name='avatar_path',
            field=models.TextField(blank=True, null=True, verbose_name='Đường dẫn ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='university',
            name='favourite_users',
            field=models.ManyToManyField(related_name='favourite_university_set', through='university.UserFavouriteUniversity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='university',
            name='manage_users',
            field=models.ManyToManyField(related_name='manage_university_set', through='university.UserManagerUniversity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='university',
            name='sectors',
            field=models.ManyToManyField(through='subject.UniversitySector', to='subject.Sector'),
        ),
        migrations.AlterField(
            model_name='university',
            name='avg_score',
            field=models.FloatField(default=0, verbose_name='Điểm trung bình'),
        ),
        migrations.AlterField(
            model_name='university',
            name='code',
            field=models.CharField(max_length=7, null=True, unique=True, verbose_name='Mã viết tắt'),
        ),
        migrations.AlterField(
            model_name='university',
            name='image_path',
            field=models.TextField(blank=True, null=True, verbose_name='Đường dẫn ảnh'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='university',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_universities', to='university.University', verbose_name='Parent University'),
        ),
        migrations.AlterField(
            model_name='university',
            name='rank',
            field=models.IntegerField(default=-1, verbose_name='Thứ hạng'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='Tổng quan'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='site_url',
            field=models.URLField(blank=True, null=True, verbose_name='Địa chỉ website'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='university',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='university.University', verbose_name='Đại hoc'),
        ),
        migrations.AlterField(
            model_name='universityscorebycriterion',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.Criterion', verbose_name='Tiêu chí so sánh'),
        ),
        migrations.AlterField(
            model_name='universityscorebycriterion',
            name='score',
            field=models.FloatField(default=0, validators=[score.validators.ScoreValidator()], verbose_name='Điểm'),
        ),
        migrations.AlterField(
            model_name='universityscorebycriterion',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='university.University', verbose_name='Đại hoc'),
        ),
        migrations.AlterField(
            model_name='universityscorebycriterioncategory',
            name='criterion_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.CriterionCategory', verbose_name='Nhóm tiêu chí'),
        ),
        migrations.AlterField(
            model_name='universityscorebycriterioncategory',
            name='score',
            field=models.FloatField(default=0, validators=[score.validators.ScoreValidator()], verbose_name='Điểm'),
        ),
        migrations.AlterField(
            model_name='universityscorebycriterioncategory',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_category_scores', to='university.University', verbose_name='Đại hoc'),
        ),
        migrations.AlterField(
            model_name='userfavouriteuniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_users_set', to='university.University', verbose_name='Đại hoc'),
        ),
        migrations.AlterField(
            model_name='userfavouriteuniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_universities_set', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='usermanageruniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_users_set', to='university.University', verbose_name='Đại hoc'),
        ),
        migrations.AlterField(
            model_name='usermanageruniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_universities_set', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
