# Generated by Django 2.0.1 on 2018-02-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_auto_20180205_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityscore',
            name='university',
        ),
        migrations.AddField(
            model_name='universityscorebycategory',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores_by_category', to='university.University'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='universityscore',
            name='score_by_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='university.UniversityScoreByCategory'),
        ),
        migrations.AlterField(
            model_name='universitysubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='subject.Subject'),
        ),
    ]
