# Generated by Django 2.0.4 on 2018-08-07 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_auto_20180731_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['id'], 'permissions': (), 'verbose_name': 'Đại hoc', 'verbose_name_plural': 'Các trường Đại học'},
        ),
    ]
