# Generated by Django 2.0.1 on 2018-02-24 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_auto_20180224_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_universities', to='university.University'),
        ),
    ]
