# Generated by Django 2.0.1 on 2018-03-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0018_auto_20180305_1351'),
        ('university', '0015_auto_20180224_0315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='universitysubject',
            unique_together={('university', 'subject')},
        ),
    ]
