# Generated by Django 2.0.1 on 2018-03-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_auto_20180312_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.Criterion'),
        ),
        migrations.AlterField(
            model_name='universityscorebycategory',
            name='category_criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.CategoryCriterion'),
        ),
    ]
