# Generated by Django 2.0.1 on 2018-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_auto_20180317_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
