# Generated by Django 2.0.1 on 2018-03-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0020_university_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitysubject',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='universitysubject',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
    ]
