# Generated by Django 2.0.1 on 2018-03-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0021_auto_20180326_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitysubject',
            name='overall_score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='universitysubject',
            name='rank',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
