# Generated by Django 2.0.1 on 2018-03-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0006_auto_20180326_0857'),
        ('university', '0022_auto_20180326_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityscorebycategory',
            old_name='category_criterion',
            new_name='criterion_category',
        ),
        migrations.AlterUniqueTogether(
            name='universityscorebycategory',
            unique_together={('university', 'criterion_category')},
        ),
    ]
